name: 🔨 Build Test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop
      - feature*
    paths:
      - '**.go'
      - '**.mod'
jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-12 ]
        go-version: [ 1.21.x ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build .
        working-directory: cmd/hednsextractor/

      - name: Test
        run: go test ./...
        working-directory: .

      - name: Install
        run: go install
        working-directory: cmd/hednsextractor/

      - name: Race Condition Tests
        run: go build -race .
        working-directory: cmd/hednsextractor/

      
